version: "3"
## configure netowrks
networks:
    web:
        external:
            name: web
## configure services
services:
  traefik:
    image: traefik:v2.4
    restart: always
    networks:
      - web
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./traefik-config/acme.json:/acme.json
      - ./traefik-config/traefik_dynamic.toml:/traefik_dynamic.toml
      - ./traefik-config/traefik.toml:/traefik.toml
      ### low security, only use in develop environment https://doc.traefik.io/traefik/providers/docker/#docker-api-access
      ### using tcp or ssh connection to docker.sock
      ### docker.sock is needed to listen to changes to containers
      - /var/run/docker.sock:/var/run/docker.sock 
