# traefik dynamic config
## rerouting to secure connection using letsencyrpt for api/dashboard service
[http.routers.api]
    rule = "Host(`dashboard.localhost`)" ### set domain for dashboard here
    entrypoints = ["web"]
    service = "api@internal"
