# main config
## route 80
[entryPoints]
    [entryPoints.web]
        address = ":80"
## enable web ui        
[api]
    dashboard = true
## configure traefik as proxy for docker 
[providers.docker]
    watch = true
    network = "web"
## enable auto discovery of docker containers
[providers.file]
    filename = "traefik_dynamic.toml"
