# main config
## reroute 80 to 443 requests
[entryPoints]
    [entryPoints.web]
        address = ":80"
        [entryPoints.web.http.redirections.entryPoint]
            to = "websecure"
            scheme = "https"

    [entryPoints.websecure]
        address = ":443"
## enable web ui        
[api]
    dashboard = true
## enable auto tls certificate via let's encrypt
[certificatesResolvers.lets-encrypt.acme]
    email = "vuong@mieli.de"
    storage = "acme.json" 
    [certificatesResolvers.lets-encrypt.acme.tlsChallenge]
## configure traefik as proxy for docker and auto discovery
[providers.docker]
    watch = true
    network = "web"
